/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as NasabahRouteImport } from './routes/nasabah'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NasabahIdRouteImport } from './routes/nasabah.$id'

const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const NasabahRoute = NasabahRouteImport.update({
  id: '/nasabah',
  path: '/nasabah',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NasabahIdRoute = NasabahIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NasabahRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/nasabah': typeof NasabahRouteWithChildren
  '/pengaturan': typeof PengaturanRoute
  '/nasabah/$id': typeof NasabahIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/nasabah': typeof NasabahRouteWithChildren
  '/pengaturan': typeof PengaturanRoute
  '/nasabah/$id': typeof NasabahIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/nasabah': typeof NasabahRouteWithChildren
  '/pengaturan': typeof PengaturanRoute
  '/nasabah/$id': typeof NasabahIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/dashboard'
    | '/import'
    | '/login'
    | '/nasabah'
    | '/pengaturan'
    | '/nasabah/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer'
    | '/dashboard'
    | '/import'
    | '/login'
    | '/nasabah'
    | '/pengaturan'
    | '/nasabah/$id'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/dashboard'
    | '/import'
    | '/login'
    | '/nasabah'
    | '/pengaturan'
    | '/nasabah/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  NasabahRoute: typeof NasabahRouteWithChildren
  PengaturanRoute: typeof PengaturanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasabah': {
      id: '/nasabah'
      path: '/nasabah'
      fullPath: '/nasabah'
      preLoaderRoute: typeof NasabahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasabah/$id': {
      id: '/nasabah/$id'
      path: '/$id'
      fullPath: '/nasabah/$id'
      preLoaderRoute: typeof NasabahIdRouteImport
      parentRoute: typeof NasabahRoute
    }
  }
}

interface NasabahRouteChildren {
  NasabahIdRoute: typeof NasabahIdRoute
}

const NasabahRouteChildren: NasabahRouteChildren = {
  NasabahIdRoute: NasabahIdRoute,
}

const NasabahRouteWithChildren =
  NasabahRoute._addFileChildren(NasabahRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  NasabahRoute: NasabahRouteWithChildren,
  PengaturanRoute: PengaturanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
